@baseUrl = http://localhost:5241
# @baseUrl = https://localhost:7093

### Health
GET {{baseUrl}}/api/diagnostics/simulate-error

###

### Create order
POST {{baseUrl}}/api/orders
Content-Type: application/json

{
  "orderNumber": "ORD-2001",
  "customerId": "11111111-1111-1111-1111-111111111111",
  "items": [
    { "productId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa", "quantity": 1 }
  ]
}

###


### Confirm order
POST {{baseUrl}}/api/orders/{{orderId}}/confirm

### Confirm order
POST {{baseUrl}}/api/orders/1a868c75-1800-447e-ba76-5e086561154c/confirm

